[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pySoftWhere"
#authors = [{name = "Rob Ziolek", email = "robert.ziolek[at]kcl.ac.uk"}]
#dynamic = ["version", "description"]
